import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    margin: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  header: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E5',
  },
  confidenceOverview: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  confidenceIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  confidenceInfo: {
    flex: 1,
  },
  confidenceLevel: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1C1C1E',
    marginBottom: 2,
  },
  confidenceScore: {
    fontSize: 14,
    color: '#8E8E93',
  },
  confidenceDescription: {
    fontSize: 14,
    color: '#1C1C1E',
    lineHeight: 20,
  },
  confidenceMeter: {
    flexDirection: 'row',
    margin: 16,
    height: 60,
    backgroundColor: '#F9F9F9',
    borderRadius: 8,
    position: 'relative',
  },
  meterSegment: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 8,
  },
  meterBar: {
    width: '80%',
    height: 8,
    borderRadius: 4,
    marginBottom: 4,
  },
  meterLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: '#1C1C1E',
  },
  confidenceIndicator: {
    position: 'absolute',
    top: 8,
    width: 20,
    height: 20,
    alignItems: 'center',
  },
  indicatorArrow: {
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderBottomWidth: 8,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    marginBottom: -2,
  },
  indicatorDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  qualityMetrics: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E5',
  },
  metric: {
    marginBottom: 16,
  },
  metricLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#1C1C1E',
    marginBottom: 8,
  },
  metricBar: {
    height: 8,
    backgroundColor: '#E5E5E5',
    borderRadius: 4,
    marginBottom: 4,
  },
  metricFill: {
    height: '100%',
    borderRadius: 4,
  },
  metricValue: {
    fontSize: 12,
    color: '#8E8E93',
    textAlign: 'right',
  },
  intervalsSection: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E5',
  },
  intervalsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1C1C1E',
    marginBottom: 12,
  },
  intervalDisplay: {
    marginBottom: 8,
  },
  intervalBar: {
    height: 12,
    backgroundColor: '#E5E5E5',
    borderRadius: 6,
    position: 'relative',
    marginBottom: 8,
  },
  intervalRange: {
    position: 'absolute',
    height: '100%',
    borderRadius: 6,
    opacity: 0.7,
  },
  intervalPoint: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderRadius: 8,
    top: -2,
    marginLeft: -8,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  intervalLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  intervalLabel: {
    fontSize: 12,
    color: '#8E8E93',
  },
  intervalCurrent: {
    color: '#007AFF',
    fontWeight: '600',
  },
  intervalNote: {
    fontSize: 12,
    color: '#8E8E93',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  uncertaintySection: {
    padding: 16,
  },
  uncertaintyTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1C1C1E',
    marginBottom: 12,
  },
  uncertaintyItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#FFF8E1',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#FF9500',
  },
  uncertaintyText: {
    fontSize: 14,
    color: '#1C1C1E',
    lineHeight: 20,
    flex: 1,
    marginLeft: 8,
  },
});